---
title: "Week 01 Announcements"
format: gfm
---

Hi, everyone:

Welcome to DATA 5600! I'm looking forward to working with and getting to know all of you.

First, please note that my office hours will need to be on Thursday only rather than Tuesday and Thursday, though I am still available by appointment as well. Also, it's come to my attention that Canvas has changed their backend and no longer supports embedded JavaScript files. That means you can download the slides from each lecture as HTML files, but you can't view them as embedded within each topic page. I'm working on a solution with the Center for Instructional Design and Innovation as we speak.

Some additional things to note as we get started this week.

- On the home page I've listed everything for each week in the order you should tackle it. Week 01 starts with a Pre-Survey, which is remotely proctored. Then the first topic is Regression and Machine Learning. Each topic page includes the relevant course material, the assigned exercise, and the associated project milestone.
- The lectures are essential! There is no assigned reading. The lectures include questions to prepare for interviews and code you will be evaluated on using and adapting in your exercises and projects. If you need to work through a given lecture multiple times, please do so.
- Pay careful attention to the syllabus. There are three types of assignments. **Exercises** are designed to help you practice what you learn in the lectures, give you the opportunity to evaluate code with the peer review assigned for each exercise, and provide an opportunity for you to talk about code when randomly assigned for a given exercise. **Projects** are the opportunity for you to, as a group, demonstrate mastery of the concepts and code, including weekly assignments where your group discusses your progress on working through the project milestones from that week. **Interviews** take the place of exams and should be something you prepare for by engaging in the lectures and applying concepts and code to exercises and especially the group projects.
- On the home page, you'll see that my office hours will be on Thursdays (**not** Tuesdays) from 3-5 pm in GLLB 218 or via Zoom. I'm also available by appointment in EBB 718 or via Zoom. The TA office hours are also by appointment via Zoom.

I've done my best to make sure your calendar and to do list help you get into the pattern of study each week: Working through lectures, practicing what you learn with the exercises, and applying what you learn to your group project via milestones. It's a lot, but this scaffolding is designed to help you stay on track and identify where you need help.

I'm always ready to help answer any questions, so please don't be a stranger!

Go Aggies!

-Marc
