---
title: "Week 05 Announcements"
format: gfm
---

Hi, everyone:

I'm super excited to see your progress taking what you're learning from the lectures and discussions, practicing with the exercises, and applying it to your projects! We are officially a third of the way through the semester, so a few reminders on pacing.

- We only have two more weeks of lectures until Week 07 which is dedicated to project work exclusively. No new topics, just executing on the presentation and report. My plan is to make the rest of the course materials and assignments available that week, but please let me know if you need to work even further in advance.
- And speaking about working in advance, I know that's not always possible! Please remember that if you need an extension on deadlines -- like if you have a big trip or other responsibility and you just can't get everything done before you leave -- please let me know and we can work things out! We're all adults here.

Have a great week and please let me and the TAs know if you have any questions!

-Marc
