---
title: "Week 06 Announcements"
format: gfm
---

Hi, everyone:

This week the Project 01 Presentation Review is due! One person from each group needs to submit a draft of your presentation slides (note that it's one of those one-off Friday due dates) to get feedback you can incorporate as you revise in preparation for the project presentation and the report due next week.

Your slides should be as close to final as you can make them! Please don't provide just an outline. You'll get feedback in time to revise, so the more complete your draft is, the more helpful the feedback will be. Next week you'll need to submit both your recorded presentation and your written report for Project 01. While you'll see an example presentation from me in this week's lectures, the TAs will also be providing their presentation slides and reports from when they took the class as some additional examples.

Please, please, please -- if you have any questions, drop into office hours or message me or the TAs to schedule another time to meet! We're happy to meet in the evening or whenever works best for you.

-Marc
