---
title: "Regression and Machine Learning"
subtitle: "DATA 5600 Introduction to Regression and Machine Learning for Analytics"
author: Marc Dotson
title-slide-attributes:
  data-background-color: "#0F2439"
format: 
  revealjs:
    theme: ../style.scss # Modified simple theme.
    slide-number: c/t    # Numbered slides current/total.
    self-contained: true # Render to a single HTML file.
execute:
  eval: false
  echo: true
---

## 

::: {font="Avallon"}
Getting Started
:::

*Summary*

- Defined marketing analytics.
- Discussed the FAQ.
- Walked through the marketing analytics process.

*Next Time*

- Getting started with R.
- Transforming data with {dplyr}.

*Artwork by @allison_horst*

# Why are you in DATA 5600?

## Marketing Analytics

Analytics is the process of **using data to inform managerial decision-making**.

- What are the key managerial decisions in marketing?
- What is the difference between *inform* and *drive*?
- What are some examples of marketing analytics in practice?

To accomplish this, in this course we will be learning to analyze data in R.

## FAQ | What am I expected to know *now*?

Nothing. (Well, nothing about coding.)

## FAQ | What makes this course different from MKTG 401?

- We focus on **secondary data** instead of **primary data**.
- Secondary data is messy and comes from many different sources.
- Coding (i.e., "advanced Excel") allows us to do almost anything.
- This is a data analysis deep dive: more details, more technical.

## FAQ | What makes this course different from MSB 325?

- This a deeper dive into data analysis.
- Class is interactive.
- Many students find they learn more.

## FAQ | Why are we using R?

R is a free, open-source programming language for statistical computing, analysis, and data science.

- Largest repository of established and new statistical techniques.
- Friendly for non-programmers.
- A very active and helpful community.
- What you can *do* with R is in high demand.

## FAQ | What are we going to do? (What can I put on my resume?)

- Visualize, wrangle, and summarize data.
- Acquire data from a variety of sources (e.g., databases, web scraping).
- Produce reports and interactive dashboards.
- Implement a variety of inferential and predictive models.

## FAQ | Wait, can't I use _____ to do that?

R is the most *accessible*, general-purpose data analysis tool I can teach you.

## FAQ | My internship/job expects me to know Python. How do I learn it?

Python is also a general-purpose data analysis tool, it just isn't as *accessible* as R is. However, many jobs require you know Python (or, increasingly, R and Python).

- Don't try and learn it at the same time as R.
- If you're interested, we can do a Python crash course.

## FAQ | How do I study for a class like this?

1. Seek learning by study and faith (D&C 109:7).
2. Prepare for class by previewing material and coming with questions.
3. Actively code, take notes, and ask questions during class.
4. Practice coding by completing exercises, referencing supplementary material as needed.
5. Review exercise solutions and note where and why your work differs.
6. Use the quizzes to gauge how well the material is understood.
7. Work with classmates and utilize office hours.
8. Download and organize all course materials, notes, and code.

## FAQ | What's the best way to learn how to code?

1. Learn by doing: Code in class and complete exercises.
2. Pay *careful* attention to details.
3. Don't code from scratch. Start with previous work and solutions.
4. Look at and emulate good code.
5. Literally sketch what transformed data should look like in the end.

## FAQ | How am I going to be graded?

|                                              |     |
| :------------------------------------------- | :-: |
| Exercises                                    | 20% |
| Quizzes                                      | 30% |
| Projects                                     | 50% |

## FAQ | How can I get help?

- Email me: [marc.dotson@byu.edu](mailto:marc.dotson@byu.edu)
- Come to office hours: Monday 1-3 pm and Wednesday 1-3 pm, or by appointment [byu.zoom.us/j/8134455359](https://byu.zoom.us/j/8134455359)
- Email the TAs: Ethan and Grace [marketing.analytics.ta@byu.edu](mailto:marketing.analytics.ta@byu.edu)
- Go to TA office hours: Tuesday 4-6 pm, Thursday 4-6 pm, and Friday 9-10 am and 11 am-2 pm [byu.zoom.us/j/5731989983](https://byu.zoom.us/j/5731989983)
- Reference slides, class notes, and supplementary material *first*
- Learn to use GitHub Copilot (eventually)

## FAQ | How is marketing analytics used in practice?

Each unit is motivated by a case study.

- We use the case study data in class.
- You'll use the case study data for the exercises.
- Each unit culminates in a project that finalizes answers for the case study.

The motivation is to provide three detailed demonstrations of how marketing analytics is used in practice.

## FAQ | How difficult is this going to be?

- The beginning of the semester can have a **steep learning curve**.
- Project weeks can be more intense than other weeks.
- Otherwise, expect the usual two hours a week for every hour spent in class (your mileage may vary).

## FAQ | How do I avoid getting overwhelmed?

> "There is no way to go from knowing nothing about a subject to knowing something about a subject without going through a period of much frustration and suckiness. Push through. You'll suck less." -Hadley Wickham

- Don't be afraid of this **learning pit**.
- You aren't alone.
- If you commit to learning, I'll gladly walk with you.
- Learn something hard now while you have help.
- Please be patient with yourself, me, and others.

## Marketing Analytics Process


## Identify | Specify the Managerial Decision and Evaluate Data

To inform managerial decision-making there needs to be a decision to begin with. Having a well-defined managerial decision is what separates data analytics from **data mining**.

What data is needed should be evaluated with the managerial decision in mind and not the *other way around*.

## Import | Acquire the Needed Data

While primary data is gathered specifically to serve the research objectives at hand, secondary data was gathered for another purpose. Consult the original and most current source whenever possible and understand its context (i.e., use the **data dictionary**).

- Who collected it?
- Why was it collected?
- When was it collected?
- What was collected?
- How was it collected?

Acquiring secondary data may require interfacing with databases, using APIs, scraping the Web, etc.

## Tidy and Transform | Wrangle the Data

Secondary data can be **messy**. Data wrangling includes whatever tidying, cleaning, mutating, munging, selecting, transforming, renaming, fusing, or filtering is needed to get the data into the needed form to summarize and model.

This can be *tedious*.

## Visualize | Summarize the Data

Summarizing data is initially about discovery. It includes computing **statistics** (i.e., numerical summaries) and **data visualization** (i.e., graphical summaries).

- Summarizing data is closely tied with data wrangling.
- Summarizing data is often not an end in itself.

## Model | Inference and Prediction

Models *extract information* from the data to inform our managerial decision.

- In order to inform the marketing mix, the models we use are often inferential.
- Some managerial decisions only rely on prediction.

## Communicate | Report and Create Data Products

Effectively communicating marketing insights brings us full circle and highlights the necessity of domain expertise.

The analyst needs to **interpret results in a way that clearly informs the managerial decision**. You may hear this referred to as "storytelling."

## Wrapping Up

*Summary*

- Defined marketing analytics.
- Discussed the FAQ.
- Walked through the marketing analytics process.

*Next Time*

- Getting started with R.
- Transforming data with {dplyr}.

*Artwork by @allison_horst*

## Exercise 01

1. Read the syllabus. 
2. Sign up for [Posit Cloud](http://posit.cloud) and join the course [here](https://posit.cloud/spaces/322372/join?access_code=_6edH0PA4_FTpmCCKGH-0p3kDHs3lEcBVlXdO3JD).
3. Email me with questions or concerns you haven't had answered and/or what topics you're most excited to cover.
4. Read the case and write how you might meet the expectations (no more than one page).
5. Submit your response as a Word document on Canvas by the beginning of class Thursday and be prepared to share with the class.

