---
title: "Asymmetric Loss"
format: gfm
---

During this class we will demonstrate communicating model results.

To share their solution for Exercise 10, the randomly selected student is **___**.

## Learn

You can also download the slides as an .html file. Once you've previewed the material and identified any questions, start watching the lecture.

## Case Overview

As a data analyst at MarketStar, you are tasked with running a lead qualification program as part of the sales efforts for an electronics company. The client will send over leads from various sources such as trade shows, online website hits, etc. and the MarketStar sales team works to convert the leads into qualified opportunities. This client runs B2B sales, meaning the sales reps on your team reach out to companies to see if they want to purchase electronics at scale. Once leads are qualified, the lead gets passed back to the client to close the sale.

If a lead is converted into a qualified opportunity and then closes, the sales team earns a $1,000 commission on the sale. However, if a lead is not not converted to a qualified opportunity, the sales rep wastes time and resources trying to convert the lead, which is an additional $500 opportunity cost in addition to the lost commission. There are too many leads for the sales reps to try and convert them all in the time allotted. For the sales effort to be successful, your task is to identify and help your sales reps work on converting leads that are likely to be qualified.

## Apply

### Exercise 11

1. Choose a concept from the course to summarize
2. [Create a meme](https://imgflip.com/memegenerator) to illustrate the concept
3. Submit your meme as a PNG on Canvas

### Milestone 11

Prepare as a group to submit a draft of your presentation slides that is as close to final as you can make it. You'll get feedback in time to revise, but the more complete your draft is, the more helpful the feedback will be.